# Generated by Django 5.1.5 on 2025-02-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvgroningen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presentatation',
            new_name='Presentation',
        ),
    ]
