# Generated by Django 5.1.5 on 2025-02-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgroningen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
