# Generated by Django 5.1.5 on 2025-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgroningen', '0007_alter_presentation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='image_position',
            field=models.CharField(choices=[('left', 'Left of Text'), ('right', 'Right of Text'), ('above', 'Above Text'), ('below', 'Below Text'), ('default', 'Default Position')], default='right', max_length=8),
        ),
    ]
