# Generated by Django 5.1.5 on 2025-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgroningen', '0008_presentation_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'Extra Large')], default='medium', max_length=10),
        ),
    ]
